---
version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment: #credentials: elastic/elastic
      - ES_JAVA_OPTS=-Xms512m -Xmx1024m
      - cluster.name=elasticsearch
      - ELASTIC_PASSWORD=elastic
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - /tmp/elasticsearch_plugins:/usr/share/elasticsearch/plugins
      - /tmp/elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:8.13.4
    container_name: logstash
    environment:
      - TZ=Africa/Johannesburg
    volumes:
      - /tmp/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:8.13.4
    container_name: kibana
    links:
      - elasticsearch:es
    depends_on:
      - elasticsearch
    environment:
      - "elasticsearch.hosts=http://es:9200"
    ports:
      - 5601:5601
