---
version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment: #credentials: elastic/elastic
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - http.host=0.0.0.0
      - script.context.ingest.cache_max_size=2000
      - script.context.processor_conditional.cache_max_size=2000
      - script.context.template.cache_max_size=2000
      - script.context.template.max_compilations_rate=unlimited
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "action.auto_create_index=.app-search-*-logs-*,-.app-search-*,+*"
      #    ports:
      #      - 9200:9200
      #      - 9300:9300
    expose: # only expose docker-internally
      - 9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cat/health?h=status | grep -q green"]
      retries: 300
      interval: 1s
    networks:
      - elastic

  logstash:
    image: logstash:8.13.4
    container_name: logstash
    environment:
      - TZ=Africa/Johannesburg
      - LS_JAVA_OPTS='-Xmx1g -Xms1g'
    depends_on:
      - elasticsearch
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600/_node/stats"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  kibana:
    image: kibana:8.13.4
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin
      - telemetry.enabled=false
      - telemetry.optIn=false
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
